# Generated by Django 5.2.8 on 2025-11-24 02:30

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='delivered_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Fecha de entrega'),
        ),
        migrations.AddField(
            model_name='order',
            name='estimated_delivery_date',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha estimada de entrega'),
        ),
        migrations.AddField(
            model_name='order',
            name='shipped_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Fecha de envío'),
        ),
        migrations.AddField(
            model_name='order',
            name='shipping_address',
            field=models.TextField(blank=True, verbose_name='Dirección de envío'),
        ),
        migrations.AddField(
            model_name='order',
            name='shipping_status',
            field=models.CharField(choices=[('PENDING', 'Pendiente de envío'), ('PREPARING', 'Preparando pedido'), ('SHIPPED', 'Enviado'), ('IN_TRANSIT', 'En tránsito'), ('OUT_FOR_DELIVERY', 'En reparto'), ('DELIVERED', 'Entregado'), ('FAILED', 'Fallo en entrega')], default='PENDING', max_length=20, verbose_name='Estado de envío'),
        ),
        migrations.AddField(
            model_name='order',
            name='tracking_number',
            field=models.CharField(blank=True, max_length=100, verbose_name='Número de seguimiento'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['tracking_number'], name='orders_orde_trackin_04edf9_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['shipping_status'], name='orders_orde_shippin_086dcd_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['-estimated_delivery_date'], name='orders_orde_estimat_84501e_idx'),
        ),
    ]
