# Generated by Django 5.2.8 on 2025-11-24 02:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MedicalRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Fecha de consulta')),
                ('diagnosis', models.TextField(verbose_name='Diagnóstico')),
                ('treatment', models.TextField(verbose_name='Tratamiento')),
                ('veterinarian', models.CharField(max_length=200, verbose_name='Veterinario')),
                ('notes', models.TextField(blank=True, verbose_name='Notas adicionales')),
                ('weight', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Peso (kg)')),
                ('temperature', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True, verbose_name='Temperatura (°C)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de registro')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última actualización')),
                ('pet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medical_records', to='pets.pet', verbose_name='Mascota')),
            ],
            options={
                'verbose_name': 'Registro Médico',
                'verbose_name_plural': 'Registros Médicos',
                'ordering': ['-date', '-created_at'],
                'indexes': [models.Index(fields=['pet', '-date'], name='pets_medica_pet_id_5c8ff6_idx'), models.Index(fields=['-date'], name='pets_medica_date_547d30_idx')],
            },
        ),
        migrations.CreateModel(
            name='Vaccine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vaccine_name', models.CharField(max_length=200, verbose_name='Nombre de la vacuna')),
                ('date_administered', models.DateField(verbose_name='Fecha de aplicación')),
                ('next_dose_date', models.DateField(blank=True, null=True, verbose_name='Próxima dosis')),
                ('veterinarian', models.CharField(max_length=200, verbose_name='Veterinario')),
                ('batch_number', models.CharField(blank=True, max_length=100, verbose_name='Número de lote')),
                ('notes', models.TextField(blank=True, verbose_name='Notas')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de registro')),
                ('pet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vaccines', to='pets.pet', verbose_name='Mascota')),
            ],
            options={
                'verbose_name': 'Vacuna',
                'verbose_name_plural': 'Vacunas',
                'ordering': ['-date_administered'],
                'indexes': [models.Index(fields=['pet', '-date_administered'], name='pets_vaccin_pet_id_229fcf_idx'), models.Index(fields=['next_dose_date'], name='pets_vaccin_next_do_f08f92_idx')],
            },
        ),
    ]
